---
- name: install openmrs on ubuntu
  become: yes
  hosts: all 
  tasks:
    - name: apt 
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: apt
      ansible.builtin.apt:
        name:  install maven    
        update_cache: true
        state: present
    - name: gitclone
      ansible.builtin.git:
         repo: https://github.com/openmrs/openmrs-core.git
         dest: openmrs-core
         clone: yes
         update: yes
    - name: build command
      ansible.builtin.shell:
         chdir: /home/ansible/openmrs-core
         cmd: mvn clean package

             